POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "John Snow",
    "email": "alex@gmail.com",
    "password": "fleming"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "alex@gmail.com",
    "password": "fleming"
}

###
GET http://localhost:5000/api/private/dashboard
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMzEzNTMxNjFmMTM4MjJkNDVlNTFjZCIsImlhdCI6MTYxMzgzNzYzNywiZXhwIjoxNjEzODM4MjM3fQ.RvCy2SimNuCpGvmAIE9onLgKGHjA91zHXiXo43EsyfU