POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Free",
    "last": "Account",
    "email": "free@account.com",
    "age": 21,
    "gender": "Male",
    "password": "123456",
    "sub": "free"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "tracy@email.com",
    "password": "pikachu"
}

###
GET http://localhost:5000/api/private/dashboard/6031373f01351b0d94e9216d
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMzEzNzNmMDEzNTFiMGQ5NGU5MjE2ZCIsImlhdCI6MTYxNDgzMTQzNywiZXhwIjoxNjE0OTE3ODM3fQ.jbzvpnlGlSIJmeP61OwOVXG4xcdnm2HP4KiC8w2Dsos

###
POST http://localhost:5000/api/private/newarticle/603e2e2416886f3b889b5087
Content-Type: application/json

{
    "title": "abc",
    "subtitle": "xyz"
}

###
POST http://localhost:5000/test/603e2e2416886f3b889b5087
Content-Type: application/json

{
    "title": "Article - test #2",
    "subtitle": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

###
# id is for articles
POST http://localhost:5000/api/private/userbyarticle/603e4b42357e5c26f83ab1b5
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwM2UyZTI0MTY4ODZmM2I4ODliNTA4NyIsImlhdCI6MTYxNDY5NDk5NiwiZXhwIjoxNjE0NzgxMzk2fQ.lKZE124aU4b0-X2L8dHYgnu2R-tnPL5wVS55QYUSHYc

###

# id is for users
POST http://localhost:5000/api/private/articlesbyuser/603e2e2416886f3b889b5087
Content-Type: application/json

###
GET http://localhost:5000/api/private/getall
Content-Type: application/json

###
GET http://localhost:5000/api/private/getuser/603e2e2416886f3b889b5087
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwM2UyZTI0MTY4ODZmM2I4ODliNTA4NyIsImlhdCI6MTYxNTA1MTg5MywiZXhwIjoxNjE1MTM4MjkzfQ.N5i4urv9qj5JHW1HKgO6vB_NweUYwzPb6j7ORnH_JI4

###
GET http://localhost:5000/article/604246c753c98b239023bc7a

###
GET http://localhost:5000/api/private/getarticle/604246c753c98b239023bc7a

###
PUT http://localhost:5000/api/private/articleupdate/604246ca53c98b239023bc7c
Content-Type: application/json

{
    "title": "Update Test",
    "subtitle": "This might just work",
    "primary": "#000",
    "secondary": "#111"
}